services:
  chatbot:
    build: .
    container_name: chatbot
    command: >
      gunicorn app:app  --bind 0.0.0.0:5000  --workers 2 --threads 20  --timeout 120  --graceful-timeout 120  --keep-alive 5  --max-requests 100  --max-requests-jitter 20 
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - redis
    networks:
      - app-network
    restart: always

  redis:
    image: redis:7
    container_name: redis
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
